---
title: Tomas Roy
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  work:
    title: Work
    output: true
  uploads:
    title: Uploads
    output: true
  writing:
    title: Writing
    output: true
background_images:
- "/uploads/57.jpg"
- "/uploads/53.jpg"
- "/uploads/40.jpg"
- "/uploads/30.jpg"
- "/uploads/41.jpg"
nav:
- title: Work
  url: "/work"
- title: Reading
  url: "/reading"
- title: Writing
  url: "/writing"
headshot: "/uploads/TomasRoy.jpg"
footer_text: Thanks for visiting! You can email me at [hello@minicreative.net](mailto:hello@minicreative.net)
sass:
  style: compressed
plugins:
- jekyll-sitemap
